apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: namespace-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ocs-storagecluster-cephfs
